### ISSUE TITLE
[BE] Swagger를 사용하여 API 문서를 작성해요. :)

### ISSUE THREAD

**Issue by seokmyungham** [woowacourse-teams/2024-momo#160]
## 이슈 요약

Swagger를 사용하여 상세한 API 문서를 제공합니다.
현재 존재하는 Swagger UI는 프로젝트 초기 작성된 프로토타입이기 때문에 제한적인 정보만 제공하고 있습니다.
이를 Swagger Annotation을 사용하여 발전시키고, 적절한 추상화를 통해 비즈니스 로직으로부터 문서화 로직을 분리합니다.

## 상세 작업 내용

- [x] API 마다 summary, description, response case를 정의합니다. 
- [x] request, response dto의 specification을 정의합니다.
- [x] 문서화 로직을 추상화하여 비즈니스 로직으로부터 분리합니다.
- [x] Profile을 통해 로컬, 개발 환경에서만 활성화하도록 설정합니다.

**Comment by hw0603** [comment]
>  Profile을 통해 개발 환경에서만 활성화하도록 설정합니다.

`dev` `local` 둘 다 활성화시키면 좋을 것 같아요! 나중에 `prod`가 생기면 그때 제외하는걸로 하죠🙂

**Comment by seokmyungham** [comment]
> dev, local 둘 다 활성화시키면 좋을 것 같아요! 나중에 prod가 생기면 그때 제외하는걸로 하죠🙂

확인했습니다 😀
말씀하신대로 진행하고 본문도 수정해놓을게요!
