### ISSUE TITLE
[FE] 프론트엔드 배포 워크플로우에서 오류가 발생해요 :(

### ISSUE THREAD

**Issue by hw0603** [woowacourse-teams/2024-momo#239]
## 이슈 요약

프론트엔드 배포 워크플로우 실행 중 `aws cli` 를 찾지 못하는 오류가 발생합니다.
실제 `aws cli` 가 설치되어 있지 않아 발생하는 문제가 아니라 2개의 Self Hosted Runner(dev/prod) 중 적절한 러너(dev)를 찾지 못하고 prod로 실행되어 발생하는 오류로 보입니다.

```log
Run aws s3 sync ./ s3://... --delete
/home/ubuntu/actions-runner/_work/_temp/8644f[7](https://github.com/woowacourse-teams/2024-momo/actions/runs/10405967328/job/28817993578#step:3:8)30-a6be-4a45-97fe-325f467e8662.sh: line 1: aws: command not found
Error: Process completed with exit code 127.
```

## 상세 작업 내용

- [x] 프론트엔드 배포 자동화 워크플로우의 self hosted runner 지정 구문에서 러너를 고유하게 식별할 수 있는 태그 추가

**Comment by Largopie** [comment]
![raccoon-rave](https://github.com/user-attachments/assets/a7e83fd7-6a6d-4771-a407-c0193e6bad6e)
