### ISSUE TITLE
[FE] 프론트엔드 리소스들을 aws에 배포하고, cd 워크플로우를 구축해요 :)

### ISSUE THREAD

**Issue by hwinkr** [woowacourse-teams/2024-momo#41]
## 이슈 요약

프론트엔드 리소스들을 aws에 배포하고, cd 워크플로우를 구축해요 :)

## 상세 작업 내용

- [x] 프론트엔드 리소들을 aws S3, CloudFront를 사용해서 배포할 수 있다.
- [x] github actions를 사용해서 cd 워크플로우를 구축할 수 있다.

**Comment by Largopie** [comment]
추가로 이슈를 생성해서 해결하셨네요!
